version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"   # cek workflow di root .github/workflows
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
