# .github/workflows/build.yml
name: Build FormatUSB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt and build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential qt5-default qttools5-dev-tools qtbase5-dev

      - name: Build FormatUSB
        run: |
          qmake
          make
